package defpackage;

/* renamed from: qj0  reason: default package */
/* compiled from: HomeDrawerOption */
public enum qj0 {
    MY_PROFILE,
    FEATURES,
    TRIP_PLANNER,
    SCHEDULER,
    NEARBY_STOPS,
    PASS,
    CABSANDAUTOS,
    FEATURE_HISTORY,
    PASS_TICKET_HISTORY,
    CAB_HISTORY,
    FAVORITES,
    FEATURE_SUPPORT,
    ALERT,
    CHAT,
    BLOG,
    SOS,
    FEATURE_OTHER,
    CHANGE_CITY,
    TRAIN_MAP,
    CHANGE_LANG,
    INVITE,
    RATE,
    REDEEM,
    UPDATE,
    PRODUCT,
    SCAN_PAY,
    SOCIAL_MEDIA,
    FEATURE_SOCIAL_MEDIA,
    TERMS,
    CITY_INFO,
    MTICKET,
    PARTNERS,
    REFERRAL,
    FOLLOW_US,
    EMPTY,
    FEATURE_DIVIDER,
    CHANGE_ENVIRONMENT,
    CARD_RECHARGES
}
